# Generated by Django 5.1.4 on 2025-01-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room",
                    models.CharField(
                        choices=[
                            ("Sala 1", "A"),
                            ("Sala 2", "B"),
                            ("Sala 3", "C"),
                            ("Sala 4", "D"),
                            ("Sala 5", "E"),
                            ("Sala 6", "F"),
                            ("Sala 7", "G"),
                        ],
                        max_length=6,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "hour",
                    models.TimeField(
                        choices=[
                            ("09", "Nueve"),
                            ("10", "Diez"),
                            ("11", "Once"),
                            ("12", "Doce"),
                            ("13", "Trece"),
                            ("14", "Catorce"),
                            ("15", "Quince"),
                            ("16", "Dieciseis"),
                            ("17", "Diecisiete"),
                            ("18", "Dieciocho"),
                        ]
                    ),
                ),
                ("user", models.TextField(blank=True)),
            ],
        ),
    ]
